disabled_rules:
  - line_length
  - unused_closure_parameter
  - trailing_comma
  - type_body_length
  - file_length
  - force_cast
opt_in_rules:
  - switch_case_on_newline
  - implicitly_unwrapped_optional
